version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - 8080:8080
    environment:
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT}
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
    networks:
      - journey

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - ${JOURNEY_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
    networks:
      - journey

networks:
  journey:
    driver: bridge